version: "2"

services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    command: postgres -c fsync=off

  hive_metastore:
    image: meneal/docker-hive:hadoop2.9.2-hive2.3.7
    volumes:
      - ./metastore-site.xml:/opt/apache-hive-3.1.2-bin/conf/hivemetastore-site.xml
      - ./metastore-log4j.properties:/opt/apache-hive-3.1.2-bin/conf/hive-log4j2.properties
    entrypoint: sh -c "bin/schematool -initSchema -dbType postgres ; bin/hive --service metastore"
    depends_on:
      - postgres

  hive:
    image: meneal/docker-hive:hadoop2.9.2-hive2.3.7
    volumes:
      - ./metastore-site.xml:/opt/apache-hive-3.1.2-bin/conf/hivemetastore-site.xml
      - ./metastore-log4j.properties:/opt/apache-hive-3.1.2-bin/conf/hive-log4j2.properties
    entrypoint: bin/hive --service hiveserver2
    ports:
      - "10000:10000"
    depends_on:
      - postgres
      - hive_metastore